---
drone_ip_addr: 127.0.0.1
drone_port: 8010

nginx_sites:
  drone:
    - listen 443 http2
    - "server_name drone.{{ inventory_hostname }}"
    - "include /etc/nginx/snippets/ssl.{{ inventory_hostname }}.conf"
    - location / {
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:8010;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_buffering off;
        chunked_transfer_encoding off;
      }

    - location ~* /ws {
        proxy_pass http://127.0.0.1:8010;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
