---
nginx_http_params:
  - client_max_body_size 50M

nginx_pkgs:
  - nginx
  - nginx-extras
  - python-selinux

nginx_configs:
  secure:
    - add_header X-Frame-Options SAMEORIGIN
    - add_header X-Content-Type-Options nosniff
    - add_header X-XSS-Protection "1; mode=block"
    - 'more_set_headers "Server: {{ inventory_hostname }}"'

  compress:
    - gzip on
    - gzip_http_version 1.1
    - gzip_comp_level 2
    - gzip_proxied expired no-cache no-store private auth
    - gzip_vary on
    - gzip_types text/plain text/css text/xml text/csv text/javascript application/x-javascript application/xml application/xml+rss application/javascript application/postscript application/pdf application/ecmascript application/json image/svg+xml
    - gzip_min_length 1000
    - gzip_disable "MSIE [1-6]\."

  "{{ inventory_hostname }}":
    - upstream {{ inventory_hostname }} {
        server 127.0.0.1:5000 fail_timeout=0;
      }
