---
nginx_auth_basic_files:
  "{{ inventory_hostname }}":
    - mongkok:$apr1$o9N1V11x$oeNkhyHHSpYA5jomb.kf51

nginx_sites:
  redirects:
    - listen 80 default_server
    - listen [::]:80 default_server
    - server_name _
    - return 301 https://$host$request_uri

  docker.{{ inventory_hostname }}:
    - listen 443 http2
    - "server_name docker.{{ inventory_hostname }}"
    - "include /etc/nginx/snippets/ssl.{{ inventory_hostname }}.conf"
    - "include /etc/nginx/snippets/auth_{{ inventory_hostname }}.conf"
    - location / {
        include /etc/nginx/snippets/proxy_headers.conf;
        proxy_pass http://127.0.0.1:10086;
      }

nginx_snippets:
  ssl:
    - 'ssl on'
    - 'ssl_protocols TLSv1 TLSv1.1 TLSv1.2'
    - 'ssl_prefer_server_ciphers on'
    - 'ssl_session_cache shared:SSL:10m'
    - 'ssl_session_timeout 30m'
    - 'ssl_buffer_size 8k'
    - 'ssl_dhparam /etc/nginx/snippets/dhparam.pem'
    # OCSP Stapling'
    - 'ssl_stapling on'
    - 'ssl_stapling_verify on'
    - 'resolver 8.8.4.4 8.8.8.8 valid=300s'
    - 'resolver_timeout 10s'
    # Enable HSTS
    - 'add_header Strict-Transport-Security max-age=31536000'
    # Ciphers'
    - 'ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4"'
    
  ssl.{{ inventory_hostname }}:
    - "ssl_certificate /etc/letsencrypt/live/{{ certbot_domain|default(inventory_hostname) }}/fullchain.pem"
    - "ssl_certificate_key /etc/letsencrypt/live/{{ certbot_domain|default(inventory_hostname) }}/privkey.pem"
    - "ssl_trusted_certificate /etc/letsencrypt/live/{{ certbot_domain|default(inventory_hostname) }}/chain.pem"
    - include /etc/nginx/snippets/ssl.conf

  proxy_headers:
    - proxy_set_header X-Real-IP $remote_addr
    - proxy_set_header X-Forwarded-For $remote_addr
    - proxy_set_header X-Forwarded-Proto $scheme
    - proxy_set_header Host $http_host
    - proxy_set_header Upgrade $http_upgrade
    - proxy_set_header Connection "upgrade"

  auth_{{ inventory_hostname }}:
    - auth_basic "Restricted"
    - auth_basic_user_file /etc/nginx/auth_basic/{{ inventory_hostname }}

  proxy_pass:
    - proxy_pass http://app_server;
    - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
    - proxy_set_header Host $http_host
    - proxy_redirect off
