---
nginx_snippets:
  ssl:
    - 'ssl on'
    - 'ssl_protocols TLSv1 TLSv1.1 TLSv1.2'
    - 'ssl_prefer_server_ciphers on'
    - 'ssl_session_cache shared:SSL:10m'
    - 'ssl_session_timeout 30m'
    - 'ssl_buffer_size 8k'
    - 'ssl_dhparam /etc/nginx/snippets/dhparam.pem'
    # OCSP Stapling'
    - 'ssl_stapling on'
    - 'ssl_stapling_verify on'
    - 'resolver 8.8.4.4 8.8.8.8 valid=300s'
    - 'resolver_timeout 10s'
    # Enable HSTS
    - 'add_header Strict-Transport-Security "max-age=31536000" always'
    # Ciphers'
    - 'ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4"'
    
  ssl.{{ inventory_hostname }}:
    - "ssl_certificate /etc/letsencrypt/live/{{ ssl_domain_name|default(domain_name) }}/fullchain.pem"
    - "ssl_certificate_key /etc/letsencrypt/live/{{ ssl_domain_name|default(domain_name) }}/privkey.pem"
    - "ssl_trusted_certificate /etc/letsencrypt/live/{{ ssl_domain_name|default(domain_name) }}/chain.pem"
    - include /etc/nginx/snippets/ssl.conf

  proxy_headers:
    - proxy_set_header X-Real-IP $remote_addr
    - proxy_set_header X-Forwarded-For $remote_addr
    - proxy_set_header X-Forwarded-Proto $scheme
    - proxy_set_header Host $http_host
    - proxy_set_header Upgrade $http_upgrade
    - proxy_set_header Connection "upgrade"

  auth_{{ inventory_hostname }}:
    - auth_basic "Restricted"
    - auth_basic_user_file /etc/nginx/auth_basic/{{ inventory_hostname }}

  proxy_pass:
    - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
    - proxy_set_header Host $http_host
    - proxy_redirect off
