---
oh_my_zsh_plugins:
  custom_virtualenv: |
    function virtualenv_prompt_info(){
      if [[ -n $VIRTUAL_ENV ]]; then
        printf "%s(%s) " "%{${fg_bold[cyan]}%}" ${${VIRTUAL_ENV}:t}
      fi
    }

    export VIRTUAL_ENV_DISABLE_PROMPT=1

oh_my_zsh_themes:
  ZSH_PROMPT: |
    local ret_status="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
    PROMPT=${DEFOCUS_PROMPT:-'${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'}

    ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
    ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
    ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
    ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
