---
language: python
python: "2.7"

addons:
  apt:
    packages:
    - python-pip

before_install:
  - deactivate
  - sudo apt-get update -qq

install:
  # Fix unmet dependencies
  - sudo apt-get install nginx

  # Install ansible
  - sudo pip install git+git://github.com/ansible/ansible.git@v2.2.3.0-1

  # Check ansible version
  - ansible --version

before_script:
  # Test directories
  - mv tests/host_vars host_vars/test
  - mv tests/inventory test
  - mv tests/keys keys/test

  # Requirements
  - ansible-galaxy install -r requirements.yml

script:
  # Syntax check
  - ansible-playbook webservers.yml -i test --syntax-check

  # Play test
  - ansible-playbook webservers.yml -i test --sudo --skip-tags=firewall
