---
- name: playbook for drone
  hosts: drone
  become: true
  vars_files:
    - group_vars/drone.yml
    - group_vars/nginx.yml
    - "keys/{{ inventory_hostname }}/drone.yml"

  roles:
    - role: drone
    - role: nginx
