---
# Vendors
- name: certbot
  src: geerlingguy.certbot

- name: docker
  src: https://github.com/angstwad/docker.ubuntu

- name: logrotate
  src: https://github.com/nickhammond/ansible-logrotate

- name: nginx
  src: https://github.com/jdauphant/ansible-role-nginx

- name: supervisor
  src: https://github.com/Oefenweb/ansible-supervisor

# me
- name: drone
  src: ansyble.drone

- name: firewall
  src: https://github.com/ansyble/role-firewall

- name: oh-my-zsh
  src: ansyble.oh-my-zsh

- name: python
  src: ansyble.python

- name: users
  src: ansyble.users
  
- name: webtier
  src: ansyble.webtier
