---
- name: playbook for webserver tier
  hosts: webservers
  become: true
  vars_files:
    - group_vars/firewall.yml
    - group_vars/logrotate.yml
    - group_vars/nginx.yml
    - group_vars/proxy.yml
    - group_vars/webtier.yml
    - group_vars/zsh.yml
    - "host_vars/{{ inventory_hostname }}/repos.yml"
    - "host_vars/{{ inventory_hostname }}/users.yml"
    - "host_vars/{{ inventory_hostname }}/webtier.yml"
    - "keys/{{ inventory_hostname }}/rsa/github.yml"
    - "keys/{{ inventory_hostname }}/vpn.yml"

  roles:
    - role: apt
    - role: firewall
    - role: logrotate
    - role: users
    - role: oh-my-zsh
    - role: python
    - role: oracle-java
    - role: node
    - role: docker
    - role: certbot
    - role: webtier

  post_tasks:
    # certificate
    - name: check cert exists
      stat:
        path: "/etc/letsencrypt/live/{{ domain_name }}"
      register: cert_exists
      when: inventory_hostname != 'test'

    - name: obtain cert
      shell: >
        letsencrypt certonly
        -d {{ domain_name }}
        -d drone.{{ domain_name }}
        -d docker.{{ domain_name }}
        -d api.{{ domain_name }}
        -d admin.{{ domain_name }}
        --rsa-key-size 4096
        --email {{ certbot_email }}
      when: inventory_hostname != 'test' and cert_exists.stat.exists == False

- name: playbook for nginx
  hosts: webservers
  become: true
  vars_files:
    - group_vars/nginx.yml
    - group_vars/proxy.yml
    - group_vars/webtier.yml
    - host_vars/webtier.yml

  pre_tasks:
    # dhparam
    - name: check dhparam exists
      stat:
        path: /etc/nginx/snippets/dhparam.pem
      register: dhparam_exists

    - name: openssl dhparam
      command: openssl dhparam -out /etc/nginx/snippets/dhparam.pem 4096
      async: 30
      when: dhparam_exists.stat.exists == False 

  roles:
    - role: nginx
