---
- name: playbook for webserver tier
  hosts: webservers
  become: true
  vars_files:
    - group_vars/firewall.yml
    - group_vars/logrotate.yml
    - group_vars/nginx.yml
    - group_vars/proxy.yml
    - group_vars/webtier.yml
    - group_vars/zsh.yml
    - "host_vars/{{ hostname }}/repos.yml"
    - "host_vars/{{ hostname }}/users.yml"
    - "keys/{{ hostname }}/rsa/github.yml"
    - "keys/{{ hostname }}/vpn.yml"

  roles:
    - role: apt
    - role: firewall
    - role: logrotate
    - role: users
    - role: oh-my-zsh
    - role: python
    - role: oracle-java
    - role: node
    - role: docker
    - role: certbot
    - role: webtier

- name: playbook for nginx
  hosts: webservers
  become: true
  vars_files:
    - group_vars/nginx.yml
    - group_vars/proxy.yml

  pre_tasks:
    # certificate
    - name: check cert exists
      stat:
        path: "/etc/letsencrypt/live/{{ hostname }}"
      register: cert_exists

    - name: obtain cert
      shell: >
        letsencrypt certonly
          -d {{ certbot_domain }}
          -d drone.{{ certbot_domain }}
          -d docker.{{ certbot_domain }}
          -d api.{{ certbot_domain }}
          -d admin.{{ certbot_domain }}
          --rsa-key-size 4096
          --email {{ certbot_email }}
      when: cert_exists.stat.exists == False 

    # dhparam
    - name: check dhparam exists
      stat:
        path: /etc/nginx/snippets/dhparam.pem
      register: dhparam_exists

    - name: openssl dhparam
      command: openssl dhparam -out /etc/nginx/snippets/dhparam.pem 4096
      async: 30
      when: dhparam_exists.stat.exists == False 

  roles:
    - role: nginx
