---
- name: playbook for webserver tier
  hosts: webservers
  become: true
  vars_files:
    - group_vars/firewall.yml
    - group_vars/logrotate.yml
    - group_vars/nginx.yml
    - group_vars/proxy.yml
    - group_vars/webtier.yml
    - group_vars/zsh.yml
    - "host_vars/{{ inventory_hostname }}/repos.yml"
    - "host_vars/{{ inventory_hostname }}/users.yml"
    - "host_vars/{{ inventory_hostname }}/webtier.yml"
    - [ "keys/{{ inventory_hostname }}/rsa/github.yml", group_vars/default.yml ]
    - "keys/{{ inventory_hostname }}/vpn.yml"

  roles:
    - role: apt
    - role: firewall
      tags: firewall
    - role: logrotate
    - role: users
    - role: oh-my-zsh
    - role: python
    - role: oracle-java
    - role: node
    - role: docker
    - role: certbot
    - role: webtier


- name: playbook for nginx
  hosts: webservers
  become: true
  vars_files:
    - group_vars/nginx.yml
    - group_vars/proxy.yml
    - group_vars/webtier.yml
    - "host_vars/{{ inventory_hostname }}/nginx.yml"
    - "host_vars/{{ inventory_hostname }}/webtier.yml"

  roles:
    - role: nginx

  post_tasks:
    # dhparam
    - name: check dhparam exists
      stat:
        path: /etc/nginx/snippets/dhparam.pem
      register: dhparam_exists

    - name: openssl dhparam
      command: openssl dhparam -out /etc/nginx/snippets/dhparam.pem 4096
      async: 3000
      when: dhparam_exists.stat.exists == False 

    # certificate
    - name: check cert exists
      stat:
        path: "/etc/letsencrypt/live/{{ domain_name }}"
      register: cert_exists
      when: inventory_hostname != 'test'

    - name: obtain cert
      shell: >
        letsencrypt certonly 
        -n -d {{ cert_domains|join(' -d ') }}
        --standalone
        --agree-tos
        --rsa-key-size 4096
        --email {{ certbot_email }}
      when: inventory_hostname != 'test' and cert_exists.stat.exists == False
