---
nginx_auth_basic_files:
  "{{ inventory_hostname }}":
    - mongkok:$apr1$o9N1V11x$oeNkhyHHSpYA5jomb.kf51

nginx_sites:
  redirects:
    - listen 80 default_server
    - listen [::]:80 default_server
    - server_name _
    - return 301 https://$host$request_uri

  docker.{{ inventory_hostname }}:
    - listen 443 http2
    - "server_name docker.{{ domain_name }}"
    - "include /etc/nginx/snippets/ssl.{{ inventory_hostname }}.conf"
    - "include /etc/nginx/snippets/auth_{{ inventory_hostname }}.conf"
    - location / {
        include /etc/nginx/snippets/proxy_headers.conf;
        proxy_pass http://127.0.0.1:10086;
      }

  "{{ inventory_hostname }}":
    - listen 443 http2
    - client_max_body_size 4G
    - server_name {{ domain_name }} api.{{ domain_name }} admin.{{ domain_name }}
    - "include /etc/nginx/snippets/ssl.{{ inventory_hostname }}.conf"
    - keepalive_timeout 5
    - location /static {
        alias /opt/apps/defocus/defocus/static;
        expires 7d;
      }
    - location /media {
        alias /opt/apps/defocus/defocus/media;
        expires 7d;
      }
    - location / {
        try_files $uri @proxy_to_app;
      }
    - location @proxy_to_app {
        include /etc/nginx/snippets/proxy_pass.conf;
        proxy_pass http://{{ inventory_hostname }};
      }
    - error_page 500 502 503 504 /500.html
    - location = /500.html {
        root /opt/apps/defocus/defocus/templates;
      }
